In [1]:
import pandas as pd

# 名古屋-神戸の独立性を検定する
# 名古屋と神戸両方に申込ある人だけ対象
df = pd.read_csv('../data/2nd-saisoku.csv')
entry_nagoya_or_kobe = (df.entry_nagoya > 0) | (df.entry_kobe > 0)
got_nagoya_and_kobe = (df.got_nagoya > 0) & (df.got_kobe > 0)
got_only_nagoya = (df.got_nagoya > 0) & (df.got_kobe == 0)
got_only_kobe = (df.got_nagoya == 0) & (df.got_kobe > 0)
got_none = (df.got_nagoya == 0) & (df.got_kobe == 0)

# クロス集計表を作る
print(len(df[entry_nagoya_or_kobe & got_nagoya_and_kobe].index)) # -> 24
print(len(df[entry_nagoya_or_kobe & got_only_nagoya].index))     # -> 123
print(len(df[entry_nagoya_or_kobe & got_only_kobe].index))       # -> 60
print(len(df[entry_nagoya_or_kobe & got_none].index))            # -> 274

24
123
60
274


In [2]:
import numpy as np
import scipy as sp
import scipy.stats

crossed = np.array([[24,60], [123,274]])

x2, p, dof, expected = sp.stats.chi2_contingency(crossed)

print("カイ二乗値: %(x2)s" %locals())
print("確率:       %(p)s" %locals())
print("自由度:     %(dof)s" %locals())

print("期待値(理論値):")
print(expected)

カイ二乗値: 0.0932823165592
確率:       0.760045119159
自由度:     1
期待値(理論値):
[[  25.67151767   58.32848233]
 [ 121.32848233  275.67151767]]


In [3]:
# 神戸-埼玉の独立性を検定する
# 神戸と埼玉両方に申込ある人だけ対象

entry_kobe_or_saitama = (df.entry_kobe > 0) | (df.entry_saitama > 0)
got_kobe_and_saitama = (df.got_kobe > 0) & (df.got_saitama > 0)
got_only_kobe = (df.got_kobe > 0) & (df.got_saitama == 0)
got_only_saitama = (df.got_kobe == 0) & (df.got_saitama > 0)
got_none = (df.got_kobe == 0) & (df.got_saitama == 0)

# クロス集計表を作る
print(len(df[entry_kobe_or_saitama & got_kobe_and_saitama].index)) # -> 64
print(len(df[entry_kobe_or_saitama & got_only_kobe].index))        # -> 20
print(len(df[entry_kobe_or_saitama & got_only_saitama].index))     # -> 413
print(len(df[entry_kobe_or_saitama & got_none].index))             # -> 75

64
20
413
75


In [4]:
crossed = np.array([[64,413], [20,75]])

x2, p, dof, expected = sp.stats.chi2_contingency(crossed)

print("カイ二乗値: %(x2)s" %locals())
print("確率:       %(p)s" %locals())
print("自由度:     %(dof)s" %locals())

print("期待値(理論値):")
print(expected)

カイ二乗値: 3.10219276927
確率:       0.078186915919
自由度:     1
期待値(理論値):
[[  70.04895105  406.95104895]
 [  13.95104895   81.04895105]]


In [5]:
# 埼玉-名古屋の独立性を検定する
# 埼玉と名古屋両方に申込ある人だけ対象

entry_saitama_or_nagoya = (df.entry_saitama > 0) | (df.entry_nagoya > 0)
got_saitama_and_nagoya = (df.got_saitama > 0) & (df.got_nagoya > 0)
got_only_saitama = (df.got_saitama > 0) & (df.got_nagoya == 0)
got_only_nagoya = (df.got_saitama == 0) & (df.got_nagoya > 0)
got_none = (df.got_saitama == 0) & (df.got_nagoya == 0)

# クロス集計表を作る
print(len(df[entry_saitama_or_nagoya & got_saitama_and_nagoya].index)) # -> 104
print(len(df[entry_saitama_or_nagoya & got_only_saitama].index))       # -> 373
print(len(df[entry_saitama_or_nagoya & got_only_nagoya].index))        # -> 43
print(len(df[entry_saitama_or_nagoya & got_none].index))               # -> 61

104
373
43
61


In [6]:
crossed = np.array([[104,43], [373,61]])

x2, p, dof, expected = sp.stats.chi2_contingency(crossed)

print("カイ二乗値: %(x2)s" %locals())
print("確率:       %(p)s" %locals())
print("自由度:     %(dof)s" %locals())

print("期待値(理論値):")
print(expected)

カイ二乗値: 16.2363637098
確率:       5.59105623558e-05
自由度:     1
期待値(理論値):
[[ 120.68674699   26.31325301]
 [ 356.31325301   77.68674699]]
